language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
python: 3.6
branches:
  only:
  - master

matrix:
  include:
    # g++
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # clang
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir data && python scripts/gen_long_bit_string.py > data/leetcode-add-binary.txt
    - ./build.sh VERBOSE=1

script: build/release/notes

