language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
python: 3.6
branches:
  only:
  - master

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir data && python scripts/gen_long_bit_string.py > data/leetcode-add-binary.txt
    - ./build.sh

script: build/release/notes

