name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run:  sudo apt-get install libboost-all-dev p7zip-full
      
    - name: Unpack Test data
      working-directory: ${{github.workspace}}
      run: |
        pwd
        ls -all
        (cd data; for i in *.7z;do 7z x $i;done) && chmod +x scripts/* && scripts/gen.sh
        
    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        ./b VERBOSE=1

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        pwd
        EXE=$(find . -type f -name notes -print)
        $EXE -d y
        
        
      
